language: node_js
node_js:
  - "stable"
services:
  - postgresql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
env:
  global:
    - PGPORT=5432
    - DB_NAME=questioner
    - DB_USER=jaman
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c "CREATE DATABASE ${DB_USER};" -U postgres
  - psql -c "CREATE USER ${DB_USER} WITH PASSWORD '123';" -U postgres

 